**Examples**<br>
Scalar arguments (including strings) result in a scalar boolean.

In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.isnull('fox')

False

In [3]:
pd.isnull(np.nan)

True

ndarrays result in an ndarray of booleans.

In [4]:
array = np.array([[2, np.nan, 3], [6, 7, np.nan]])
array

array([[ 2., nan,  3.],
       [ 6.,  7., nan]])

In [5]:
pd.isnull(array)

array([[False,  True, False],
       [False, False,  True]])

For indexes, an ndarray of booleans is returned.

In [6]:
index = pd.DatetimeIndex(["2019-08-04", "2019-08-05", None,
                          "2019-08-08"])
index

DatetimeIndex(['2019-08-04', '2019-08-05', 'NaT', '2019-08-08'], dtype='datetime64[ns]', freq=None)

In [7]:
pd.isnull(index)

array([False, False,  True, False])

For Series and DataFrame, the same type is returned, containing booleans.

In [8]:
df = pd.DataFrame([['cat', 'bat', 'rat'], ['fox', None, 'fly']])
df

0     1    2
0  cat   bat  rat
1  fox  None  fly

In [9]:
pd.isnull(df)

0      1      2
0  False  False  False
1  False   True  False

In [10]:
pd.isnull(df[1])

0    False
1     True
Name: 1, dtype: bool