**Examples**<br>
Scalar arguments (including strings) result in a scalar boolean.

In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.isna('fox')

False

In [3]:
pd.isna(np.nan)

True

ndarrays result in an ndarray of booleans.

In [4]:
array = np.array([[2, np.nan, 4], [5, 6, np.nan]])
array

array([[ 2., nan,  4.],
       [ 5.,  6., nan]])

In [5]:
pd.isna(array)

array([[False,  True, False],
       [False, False,  True]])

For indexes, an ndarray of booleans is returned.

In [6]:
index = pd.DatetimeIndex(["2019-05-02", "2019-05-03", None,
                          "2019-05-05"])
index

DatetimeIndex(['2019-05-02', '2019-05-03', 'NaT', '2019-05-05'], dtype='datetime64[ns]', freq=None)

In [7]:
pd.isna(index)

array([False, False,  True, False])

For Series and DataFrame, the same type is returned, containing booleans.

In [8]:
df = pd.DataFrame([['lion', 'bee', 'cow'], ['fox', None, 'fly']])
df

0     1    2
0  lion   bee  cow
1   fox  None  fly

In [9]:
pd.isna(df)

0      1      2
0  False  False  False
1  False   True  False

In [10]:
pd.isna(df[1])

0    False
1     True
Name: 1, dtype: bool